sudo: required

language: go

services:
  - docker

install:
  - vendor/go-bindata-Linux -pkg assets -o assets/assets.go ./schema/*
  - go get github.com/ngageoint/seed-common/...
  - go get golang.org/x/sys/unix/...
  - go get github.com/zyxar/image2ascii/ascii

script:
  - echo "Validating formatting with gofmt..."
  - gofmt -l . | grep -v assets\.go | if [[ $(wc -l | sed 's/ //g')>0 ]] ; then echo gofmt should be run on $(gofmt -l . | grep -v assets\.go); exit 1 ;fi
  - ./build-cli.sh ${TRAVIS_TAG}
  - docker run -d -p 5000:5000 --restart=always --name registry -v `pwd`/auth:/auth -e "REGISTRY_AUTH=htpasswd" -e "REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm" -e REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd registry:2
  - go test ./...

deploy:
  # Deployment that pushes GitHub releases of software on tag
  - provider: releases
    api_key: "$GH_TOKEN"
    file_glob: true
    file: output/*
    skip_cleanup: true
    on:
      tags: true

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/10070a680400c55e3baa
    on_success: change
    on_failure: always
    on_start: never
